
import time
import os

print( "oh no! something bad happened to Beep!")
print("do you want to help him? yes or no?")
user = input()
if user == "no" :
  print("You don't want to help beep... he feels sad...")
if user == "yes" :
  print("Great! first he needs to know some things about you..")
  print("")
  print("For instance.. your age...")
  age = int(input())
  print("Okay so you're {} apparently..".format(age))
  print("")
  print("What about your height?")
  height = float(input())
  print("Hmm.. {} ... are you really that tall? Okay then.".format(height))
  print()
  print("\041 Give him five seconds.. his systems are loading..")
  time.sleep(5)
  def clear(): os.system('clear') 
  clear()
  print("He's feeling a bit sad, maybe some love would help me feel better..")
  print()
  print("So Basically you can him  as many ♥ as you want, just choose a quantity.")
  heart = int(input())
  print("Thank you so much!! you gave him ","♥"* heart)
  print("")
  print("Since we're talking about health..")
  print("You see.. beep's mother wants to know her BMI...")
  print("So I'll ask nicely for you to type her weight..")
  weight = int(input())
  print("And now her height please..")
  height = float(input())
  bmi = weight / (height**2) 
  print(" So beeps mom BMI is  {:.2f}.".format(bmi))
  time.sleep(5)
  clear()
  print("Thank you for interacting with beep! he sure enjoyed it!")
